### ISSUE TITLE
Excuse me, is this normal

### ISSUE THREAD

**Issue by INV-PLA** [SrRapero720/DimensionalThreading-Reforked#26]
dimthread (v1.0.5)
Server thread73.32%
me.srrapero720.dimthread.thread.ThreadPool.awaitCompletion()73.32%
me.srrapero720.dimthread.thread.ThreadPool.waitFor()73.32%
me.srrapero720.dimthread.thread.ThreadPool$IntLatch.waitUntil()73.32%
java.lang.Object.wait()73.28%
java.lang.Object.wait()73.28%
java.lang.Object.wait0()73.28%
me.srrapero720.dimthread.thread.ThreadPool$IntLatch.getCount()0.04%

**Comment by SrRapero720** [comment]
yes, because all the work is delegated to other threads
server thread is just waiting, thats why `wait()` eats all the usage on the stackstrace
